### ISSUE TITLE
Botones de compartir por redes sociales

### ISSUE THREAD

**Issue by jesusmartinoza** [jesusmartinoza/COVID-19-MX#2]
Modificar el front para que se pueda compartir el sitio

**Comment by SandraMarcelaHerreraArriaga** [comment]
I am going to work on this pull request :)

**Comment by jesusmartinoza** [comment]
:D Gracias Sandra

**Comment by jesusmartinoza** [comment]
Botones agregados en PR https://github.com/jesusmartinoza/COVID-19-MX/pull/5
